### ISSUE TITLE
vocab_50000.bpe

### ISSUE THREAD

**Issue by pavelxx1** [vlarine/ruGPT2#1]
Hi
First - thx for your hardwork
I am new in ML such in GPT-2

Where I can find your vocab_50000.bpe or must create my own?
Thx,Бро)

**Comment by vlarine** [comment]
There is my vocab file: https://drive.google.com/open?id=1s9Ak-V9upxtC3utqOLxWdi_X2ZnLog2i

But you can train your own: https://github.com/VKCOM/YouTokenToMe
```
youtokentome.BPE.train(data, model, vocab_size, coverage, n_threads=-1, pad_id=0, unk_id=1, bos_id=2, eos_id=3)
```

**Comment by pavelxx1** [comment]
Thanks. Just create my own vocab model.
and I have.. error :( 
Vladimir, can you help me with issues? Thx

using world size: 1 and model-parallel size: 1 
 > using dynamic loss scaling
> initializing model parallel with size 1
Pretrain GPT2 model
arguments:
  pretrained_bert .............. False
  attention_dropout ............ 0.1
  num_attention_heads .......... 16
  hidden_size .................. 128
  intermediate_size ............ None
  num_layers ................... 8
  layernorm_epsilon ............ 1e-05
  hidden_dropout ............... 0.1
  max_position_embeddings ...... 128
  vocab_size ................... 50000
  deep_init .................... False
  make_vocab_size_divisible_by . 128
  fp16 ......................... True
  fp32_embedding ............... False
  fp32_layernorm ............... False
  fp32_tokentypes .............. False
  fp32_allreduce ............... False
  hysteresis ................... 2
  loss_scale ................... None
  loss_scale_window ............ 1000
  min_scale .................... 1
  batch_size ................... 2
  weight_decay ................. 0.01
  checkpoint_activations ....... True
  checkpoint_num_layers ........ 1
  clip_grad .................... 1.0
  train_iters .................. 32000
  log_interval ................. 100
  exit_interval ................ None
  tensorboard_dir .............. /content/drive/My Drive/ruGPT2/output0/logs/gpt2_345m
  seed ......................... 1234
  reset_position_ids ........... False
  reset_attention_mask ......... False
  eod_mask_loss ................ False
  lr_decay_iters ............... None
  lr_decay_style ............... cosine
  lr ........................... 0.00015
  min_lr ....................... 0.0
  warmup ....................... 0.01
  override_lr_scheduler ........ False
  use_checkpoint_lr_scheduler .. False
  save ......................... /content/drive/My Drive/ruGPT2/output0/checkpoints/gpt2_345m
  save_interval ................ 1000
  no_save_optim ................ False
  no_save_rng .................. False
  load ......................... /content/drive/My Drive/ruGPT2/output0/checkpoints/gpt2_345m
  no_load_optim ................ False
  no_load_rng .................. False
  finetune ..................... False
  resume_dataloader ............ True
  distributed_backend .......... nccl
  DDP_impl ..................... local
  local_rank ................... 0
  adlr_autoresume .............. False
  adlr_autoresume_interval ..... 1000
  eval_batch_size .............. None
  eval_iters ................... 100
  eval_interval ................ 1000
  eval_seq_length .............. None
  eval_max_preds_per_seq ....... None
  overlapping_eval ............. 32
  cloze_eval ................... False
  strict_lambada ............... False
  eval_hf ...................... False
  load_openai .................. False
  temperature .................. 1.0
  greedy ....................... False
  top_p ........................ 0.0
  top_k ........................ 0
  out_seq_length ............... 1024
  sample_input_file ............ 
  sample_output_file ........... 
  num_samples .................. 0
  genfile ...................... None
  recompute .................... False
  model_parallel_size .......... 1
  shuffle ...................... False
  train_data ................... ['/content/drive/My Drive/ruGPT2/output0/train.json']
  use_npy_data_loader .......... False
  train_data_path .............. 
  val_data_path ................ 
  test_data_path ............... 
  input_data_sizes_file ........ sizes.txt
  delim ........................ ,
  text_key ..................... text
  eval_text_key ................ None
  valid_data ................... None
  split ........................ 949,50,1
  test_data .................... None
  lazy_loader .................. True
  loose_json ................... True
  presplit_sentences ........... False
  num_workers .................. 2
  tokenizer_model_type ......... bert-large-uncased
  tokenizer_path ............... /content/drive/My Drive/ruGPT2/input0/example.model
  tokenizer_type ............... RubertaBPETokenizer
  cache_dir .................... cache
  use_tfrecords ................ False
  seq_length ................... 128
  max_preds_per_seq ............ None
  cuda ......................... True
  rank ......................... 0
  world_size ................... 1
  dynamic_loss_scale ........... True
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
configuring data
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 680, in <module>
    main()
  File "pretrain_gpt2.py", line 619, in main
    args.eod_token = get_train_val_test_data(args)
  File "pretrain_gpt2.py", line 549, in get_train_val_test_data
    args)
  File "/content/drive/My Drive/ruGPT2/configure_data.py", line 34, in apply
    return make_loaders(args)
  File "/content/drive/My Drive/ruGPT2/configure_data.py", line 171, in make_loaders
    train, tokenizer = data_utils.make_dataset(**data_set_args)
  File "/content/drive/My Drive/ruGPT2/data_utils/__init__.py", line 126, in make_dataset
    ds = [GPT2Dataset(d, max_seq_len=seq_length) if d is not None else None for d in ds]
  File "/content/drive/My Drive/ruGPT2/data_utils/__init__.py", line 126, in <listcomp>
    ds = [GPT2Dataset(d, max_seq_len=seq_length) if d is not None else None for d in ds]
  File "/content/drive/My Drive/ruGPT2/data_utils/datasets.py", line 479, in __init__
    self.init_weighting()
  File "/content/drive/My Drive/ruGPT2/data_utils/datasets.py", line 489, in init_weighting
    self.weighting = list(accumulate(lens))
TypeError: iteration over a 0-d array
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
